apiVersion: v1
kind: Service
metadata:
  name: public-api-flask-service-4000-v2
spec:
  selector:
    app: public-api-flask-4000-v2
  ports:
  - protocol: "TCP"
    port: 4000
    targetPort: 4000
    nodePort: 30007
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-api-flask-4000-v2
spec:
  selector:
    matchLabels:
      app: public-api-flask-4000-v2
  replicas: 1
  template:
    metadata:
      labels:
        app: public-api-flask-4000-v2
    spec:
      containers:
      - name: public-api-flask
        image: oburninova/flask_app:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 4000